name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies xrdp pulseaudio pulseaudio-module-xrdp alsa-utils ubuntu-drivers-common

    - name: Install graphics drivers
      run: |
        sudo ubuntu-drivers autoinstall
        sudo reboot

    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
    
    - name: Extract ngrok
      run: unzip ngrok.zip
    
    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Setup xfce4 session for xrdp
      run: echo "startxfce4" > ~/.xsession

    - name: Start xrdp service
      run: sudo systemctl enable xrdp && sudo systemctl start xrdp
    
    - name: Create Tunnel
      run: ./ngrok tcp 3389
