name: CI

on:
  push:
  workflow_dispatch:
    inputs:
      remote_desktop_pin:
        description: 'Enter the PIN for Chrome Remote Desktop'
        required: true
        type: string
      remote_desktop_code:
        description: 'Enter the CODE for Chrome Remote Desktop'
        required: true
        type: string

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip curl

    - name: Download and Install ngrok
      run: |
        wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
        unzip ngrok.zip -d ngrok
        chmod +x ngrok/ngrok

    - name: Authenticate ngrok
      run: ./ngrok/ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Install Chromium
      run: |
        sudo apt-get install -y chromium-browser
        # Check if /usr/bin/chromium exists, if not, create the symlink
        if [ ! -f /usr/bin/chromium ]; then
          sudo ln -sf /usr/lib/chromium-browser/chromium-browser /usr/bin/chromium
        fi

    - name: Install OBS Studio
      run: |
        sudo add-apt-repository ppa:obsproject/obs-studio -y
        sudo apt-get update
        sudo apt-get install -y obs-studio

    - name: Download and Install Chrome Remote Desktop
      run: |
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo apt-get install -y ./chrome-remote-desktop_current_amd64.deb

    - name: Configure Chrome Remote Desktop
      run: |
        echo "Configuring Chrome Remote Desktop with provided PIN and CODE"
        sudo DISPLAY= chrome-remote-desktop --setup --pin="${{ github.event.inputs.remote_desktop_pin }}" --code="${{ github.event.inputs.remote_desktop_code }}"
      env:
        REMOTE_DESKTOP_PIN: ${{ github.event.inputs.remote_desktop_pin }}
        REMOTE_DESKTOP_CODE: ${{ github.event.inputs.remote_desktop_code }}

    - name: Start Chromium
      run: |
        chromium --no-sandbox --disable-gpu &  # Running in background

    - name: Create ngrok Tunnel for RDP (port 3389)
      run: |
        ./ngrok/ngrok tcp 3389 --log=stdout &
        sleep 5  # Give ngrok time to establish the tunnel
        curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url'
