name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies pulseaudio pulseaudio-utils alsa-utils dbus-x11
        sudo apt-get install -y wget unzip
    
    - name: Download ngrok
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
    
    - name: Extract ngrok
      run: unzip ngrok.zip
    
    - name: Authenticate ngrok
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}

    - name: Start PulseAudio
      run: pulseaudio --start
    
    - name: Create Tunnel
      run: ./ngrok tcp 5901
