name: CI

on: 
  workflow_dispatch:
    inputs:
      hostname:
        description: 'Enter Hostname'
        required: true
        default: 'ubuntu'
      username:
        description: 'Enter Username'
        required: true
        default: 'user'
      password:
        description: 'Enter Password'
        required: true
        default: 'root'
      pin:
        description: 'Enter a Pin (more or equal to 6 digits)'
        required: true
        default: '123456'
      display_command:
        description: 'Paste the command from Chrome Remote Desktop setup'
        required: true
        default: ''

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y xfce4 xfce4-goodies pulseaudio pulseaudio-utils alsa-utils wget curl
        wget https://dl.google.com/linux/direct/chrome-remote-desktop_current_amd64.deb
        sudo dpkg -i chrome-remote-desktop_current_amd64.deb || sudo apt-get install -f -y
    
    - name: Set up user and password
      run: |
        sudo usermod -aG chrome-remote-desktop ${{ github.event.inputs.username }}
        echo -e "${{ github.event.inputs.password }}\n${{ github.event.inputs.password }}" | sudo passwd ${{ github.event.inputs.username }}

    - name: Configure Chrome Remote Desktop
      run: |
        DISPLAY= ${{ github.event.inputs.display_command }}
      env:
        PIN: ${{ github.event.inputs.pin }}
