name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Download
      run: wget https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip -O ngrok.zip
    - name: Extract
      run: unzip ngrok.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install xrdp
      run: |
        sudo apt-get update
        sudo apt-get install -y xrdp
    - name: Configure xrdp
      run: |
        echo "gnome-session" > ~/.xsession
        sudo systemctl enable xrdp --now
    - name: Set Password
      run: echo "runneradmin:P@ssw0rd!" | sudo chpasswd
    - name: Create Tunnel
      run: ./ngrok tcp 3389
