name: CI

on:
  workflow_dispatch:
    inputs:
      chrome_rd_auth_code:
        description: 'Chrome Remote Desktop Auth Code'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Chrome Remote Desktop Host
      run: Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "$env:TEMP\chromeremotedesktophost.msi"
      shell: pwsh

    - name: Install Chrome Remote Desktop Host
      run: Start-Process msiexec.exe -ArgumentList '/i "$env:TEMP\chromeremotedesktophost.msi" /quiet /norestart' -Wait
      shell: pwsh

    - name: Configure and Start Chrome Remote Desktop Host
      run: |
        $authCode = "${{ github.event.inputs.chrome_rd_auth_code }}"
        $pin = "123123"
        $hostExe = "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe"
        
        & $hostExe --code="$authCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name="$Env:COMPUTERNAME" --pin="$pin"
        
        if ($LASTEXITCODE -ne 0) {
            exit $LASTEXITCODE
        }
      shell: pwsh

    - name: Create Firewall Rule
      run: |
        $crdHostPath = "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_host.exe"
        New-NetFirewallRule -DisplayName "Chrome Remote Desktop" -Direction Outbound -Program $crdHostPath -Action Allow
      shell: pwsh
      
    - name: Keep Runner Alive
      run: |
        Start-Service -Name remoting
        Start-Sleep -Seconds 21600
      shell: pwsh
