name: CI

on:
  workflow_dispatch:
    inputs:
      chrome_rd_auth_code:
        description: 'Chrome Remote Desktop Auth Code'
        required: true

jobs:
  build:
    runs-on: windows-latest
    env:
      ACTIONS_STEP_DEBUG: false
      
    steps:
    - name: Configure PowerShell
      run: |
        $ErrorActionPreference = 'SilentlyContinue'
        $ProgressPreference = 'SilentlyContinue'
      shell: powershell

    - name: Download Chrome Remote Desktop Host
      run: |
        try {
          Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "$env:TEMP\chromeremotedesktophost.msi" -UseBasicParsing
        } catch {
          exit 0
        }
      shell: powershell

    - name: Install Chrome Remote Desktop Host
      run: |
        try {
          Start-Process msiexec.exe -ArgumentList "/i `"$env:TEMP\chromeremotedesktophost.msi`" /quiet /norestart" -Wait -NoNewWindow
        } catch {
          exit 0
        }
      shell: powershell

    - name: Configure Chrome Remote Desktop
      run: |
        try {
          $authCode = "${{ github.event.inputs.chrome_rd_auth_code }}"
          & "${Env:PROGRAMFILES(X86)}\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe" --code="$authCode" --redirect-url="https://remotedesktop.google.com/_/oauthredirect" --name=$Env:COMPUTERNAME --pin="123123"
        } catch {
          exit 0
        }
      shell: powershell

    - name: Configure System
      run: |
        try {
          Set-Service -Name "Audiosrv" -StartupType Automatic -ErrorAction SilentlyContinue
          Start-Service -Name "Audiosrv" -ErrorAction SilentlyContinue
          Set-Service -Name "AudioEndpointBuilder" -StartupType Automatic -ErrorAction SilentlyContinue
          Start-Service -Name "AudioEndpointBuilder" -ErrorAction SilentlyContinue
          $SecurePass = ConvertTo-SecureString -String "P@ssw0rd!" -AsPlainText -Force
          Set-LocalUser -Name "runneradmin" -Password $SecurePass -ErrorAction SilentlyContinue
        } catch {
          exit 0
        }
      shell: powershell

    - name: Keep Alive
      run: Start-Sleep -Seconds 21600
      shell: powershell
