name: CI

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y qemu qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager x11vnc xvfb
    - name: Download Arch Linux ISO
      run: wget https://mirror.rackspace.com/archlinux/iso/latest/archlinux-x86_64.iso -O archlinux.iso
    - name: Create Disk Image
      run: qemu-img create -f qcow2 archlinux.img 20G
    - name: Start VNC Server
      run: |
        Xvfb :1 -screen 0 1024x768x16 &
        x11vnc -display :1 -N -forever -shared -rfbport 5900 &
    - name: Run Arch Linux Installer
      run: |
        sudo qemu-system-x86_64 \
          -m 2G \
          -cdrom archlinux.iso \
          -drive file=archlinux.img,format=qcow2 \
          -boot d \
          -enable-kvm \
          -net nic \
          -net user \
          -vnc :1 \
          -nographic \
          -no-reboot &
    - name: Start Gnome Terminal
      run: |
        DISPLAY=:1 gnome-terminal &
    - name: Keep Alive
      run: sleep 1h
