name: CI

on:
  workflow_dispatch:
    inputs:
      chrome_rd_auth_code:
        description: 'Chrome Remote Desktop Auth Code'
        required: true

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Download Chrome Remote Desktop Host
      run: |
        Invoke-WebRequest -Uri "https://dl.google.com/edgedl/chrome-remote-desktop/chromeremotedesktophost.msi" -OutFile "chromeremotedesktophost.msi"
      shell: powershell

    - name: Install Chrome Remote Desktop Host
      run: |
        msiexec /i chromeremotedesktophost.msi /quiet /norestart
      shell: powershell

    - name: Configure Chrome Remote Desktop
      run: |
        $authCode = "${{ github.event.inputs.chrome_rd_auth_code }}"
        cmd.exe /c "`"$env:ProgramFilesX86\Google\Chrome Remote Desktop\CurrentVersion\remoting_start_host.exe`" --code=`"$authCode`" --redirect-url=`"https://remotedesktop.google.com/_/oauthredirect`" --name=`"%COMPUTERNAME%`""
      shell: powershell

    - name: Ensure Windows Audio Services are Running
      run: |
        Set-Service -Name "Audiosrv" -StartupType Automatic
        Start-Service -Name "Audiosrv"
        Set-Service -Name "AudioEndpointBuilder" -StartupType Automatic
        Start-Service -Name "AudioEndpointBuilder"
      shell: powershell

    - name: Set Runner Admin Password
      run: |
        Set-LocalUser -Name "runneradmin" -Password (ConvertTo-SecureString -AsPlainText "P@ssw0rd!" -Force)
      shell: powershell

    - name: Keep Workflow Alive for Access
      run: |
        Start-Sleep -Seconds 21600
      shell: powershell
